---
- name: Configure OPS445 CentOS VM
  hosts: rnlimon
  remote_user: student
  become: yes

  vars:
    seneca_id: rnlimon
    ssh_pubkey_path: /home/rnlimon/.ssh/id_rsa.pub

  tasks:
    - name: Ensure Apache (httpd) is updated
      yum:
        name: httpd
        state: latest

    - name: Ensure EPEL repository is installed
      yum:
        name: epel-release
        state: present

    - name: Remove 'tree' package if installed
      yum:
        name: tree
        state: absent

    - name: Set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: Create user with sudo access
      user:
        name: "{{ seneca_id }}"
        shell: /bin/bash
        groups: wheel
        state: present
        create_home: yes

    - name: Allow passwordless SSH access for new user
      authorized_key:
        user: "{{ seneca_id }}"
        state: present
        key: "{{ lookup('file', ssh_pubkey_path) }}"

    - name: Create lab directories for OPS445 labs 1 to 8
      file:
        path: "/home/{{ seneca_id }}/ops445/{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ query('sequence', 'start=1 end=8 format=lab%d') }}"
